"""Report building (Telegram HTML + email HTML/plain)."""
from __future__ import annotations

from collections import Counter
from datetime import datetime
from html import escape


def _stats_line(jobs: list[dict]) -> str:
    by_source = Counter(j.get("source", "?") for j in jobs)
    parts = [f"{src}: {n}" for src, n in sorted(by_source.items())]
    return ", ".join(parts) if parts else "—"


def telegram_report(jobs: list[dict], suggestion: str, period: str = "today") -> str:
    date = datetime.now().strftime("%d.%m.%Y")
    head = f"<b>🔎 JobScout — {period} report ({date})</b>\n"
    head += f"New jobs found: <b>{len(jobs)}</b>  ({_stats_line(jobs)})\n\n"
    ranked = sorted(jobs, key=lambda j: float(j.get("score") or 0), reverse=True)[:15]
    body = ""
    for j in ranked:
        body += (f"• <a href=\"{escape(j.get('url',''))}\">{escape(j['title'])}</a>"
                 f" — {escape(j.get('company','') or '?')}, {escape(j.get('location',''))}"
                 f" <i>[{escape(str(j.get('source','')))}, score {j.get('score')}]</i>\n")
    if not ranked:
        body = "No new jobs matched your filters in this period.\n"
    sugg = f"\n<b>💡 Recommendation</b>\n{escape(suggestion)}" if suggestion else ""
    msg = head + body + sugg
    return msg[:4000]  # Telegram hard limit is 4096 chars


def email_report(jobs: list[dict], suggestion: str, period: str = "today") -> tuple[str, str]:
    """Returns (plain_text, html)."""
    date = datetime.now().strftime("%d.%m.%Y")
    ranked = sorted(jobs, key=lambda j: float(j.get("score") or 0), reverse=True)

    plain = [f"JobScout — {period} report ({date})",
             f"New jobs found: {len(jobs)} ({_stats_line(jobs)})", ""]
    for j in ranked:
        plain.append(f"- {j['title']} — {j.get('company','?')} ({j.get('location','')}) "
                     f"[{j.get('source')}, score {j.get('score')}] {j.get('url','')}")
    if suggestion:
        plain += ["", "RECOMMENDATION", suggestion]

    rows = "".join(
        f"<tr><td><a href='{escape(j.get('url',''))}'>{escape(j['title'])}</a></td>"
        f"<td>{escape(j.get('company','') or '')}</td>"
        f"<td>{escape(j.get('location','') or '')}</td>"
        f"<td>{escape(str(j.get('source','')))}</td>"
        f"<td style='text-align:center'>{j.get('score')}</td></tr>"
        for j in ranked
    ) or "<tr><td colspan='5'>No new jobs matched your filters in this period.</td></tr>"
    sugg_html = (f"<h3>💡 Recommendation</h3><pre style='white-space:pre-wrap;"
                 f"font-family:inherit'>{escape(suggestion)}</pre>") if suggestion else ""
    html = f"""<html><body style="font-family:Arial,sans-serif;color:#222">
<h2>🔎 JobScout — {period} report ({date})</h2>
<p>New jobs found: <b>{len(jobs)}</b> ({escape(_stats_line(jobs))})</p>
<table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse;font-size:14px">
<tr style="background:#1F4E79;color:#fff"><th>Title</th><th>Company</th><th>Location</th><th>Source</th><th>Score</th></tr>
{rows}
</table>
{sugg_html}
<p style="color:#888;font-size:12px">Generated by JobScout · full history in data/jobs.xlsx</p>
</body></html>"""
    return "\n".join(plain), html
